### ISSUE TITLE
[Feature Request] Client sided hiding?

### ISSUE THREAD

**Issue by HowardZHY** [replaceitem/secret-spectator#2]

**Comment by replaceitem** [comment]
Please explain

**Comment by HowardZHY** [comment]
Hide spectator players and works when only install the mod on client side

**Comment by replaceitem** [comment]
So that it shows spectators without the transparent text?

**Comment by HowardZHY** [comment]
Can be, or don't show them at all but doesn't require server side to install

**Comment by replaceitem** [comment]
What is your use case?

**Comment by HowardZHY** [comment]
don't want weird players in tab list in whatever servers

**Comment by replaceitem** [comment]
I still don't really get why that would be much useful, but in any case the implementation would differ from what this mod is doing. So this would be a seperate mod.
